name: Sihirli Kütüphaneci İndeksleyici ve Derleyici

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: İndeksleyiciyi Çalıştır
      run: python indexer.py
      
    - name: E-Kitap Derleyiciyi Çalıştır
      run: python builder.py
      
    - name: Değişiklikleri Kaydet
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'action@github.com'
        git add indeks.json E-KITAP.md
        git commit -m "Otomatik indeks ve E-Kitap güncellendi" || echo "Değişiklik yok"
        git push
